#!/bin/bash

var=$(aconnect -o|grep M8)
var2=$(aconnect -o|grep XYXYX)
var3=$(ps aux|grep [p]ulseaudio_config)

while : 
do

if [ "$var" = "$var2" ]
 then 
  var=$(aconnect -o|grep M8)
  sleep 1
 else 
  if [ "$var2" = "$var3" ] 
  then 
   sudo pulseaudio --start --file=pulseaudio_config.pa
   var3=$(ps aux|grep [p]ulseaudio_config)
   sleep 1
  else
   sleep 2
fi
fi

done

